import type { Tx } from "../lang";
import type { PageDef } from "./types";

const tx = (ar: string, en: string): Tx => ({ ar, en });

export const PAGES: PageDef[] = [
  { id: "cover", kind: "cover", tone: "ink", chapter: "why" },

  {
    id: "problem",
    kind: "page",
    tone: "paper",
    chapter: "why",
    layout: "problem",
    kicker: tx("01 · السبب", "01 · WHY"),
    title: tx("المشكلة مش إن عندك بيانات قليلة.\nالمشكلة إن كل قسم شايف جزء من الصورة.", "The problem is not too little data.\nEvery department sees only a piece of the picture."),
    lede: tx("التسويق شايف الحملات، السيلز شايف الليدز، المالية شايفة الأرقام — والإدارة محتاجة الصورة كاملة.", "Marketing sees campaigns, sales sees leads, finance sees numbers — leadership needs the whole picture."),
    left: [
      { icon: "megaphone", title: tx("التسويق", "Marketing") },
      { icon: "handshake", title: tx("السيلز", "Sales") },
      { icon: "stack", title: tx("المخزون", "Inventory") },
      { icon: "ledger", title: tx("المالية", "Finance") },
      { icon: "people", title: tx("الموارد البشرية", "HR") },
      { icon: "chart", title: tx("التقارير", "Reports") },
    ],
    right: [
      { icon: "megaphone", title: tx("التسويق", "Marketing") },
      { icon: "handshake", title: tx("السيلز", "Sales") },
      { icon: "stack", title: tx("المخزون", "Inventory") },
      { icon: "ledger", title: tx("المالية", "Finance") },
      { icon: "radar", title: tx("الإدارة", "Management") },
    ],
    value: tx("ROOTK بيربط شغل الشركة كلها من أول مصدر الليد لحد ما الإدارة تاخد قرارها.", "ROOTK connects the company’s work from the first Lead source through to the management decision."),
  },

  {
    id: "what",
    kind: "page",
    tone: "ink",
    chapter: "arch",
    layout: "mind",
    kicker: tx("02 · البنية", "02 · ARCHITECTURE"),
    title: tx("ROOTK مش برامج متفرّقة.\nROOTK نظام تشغيل للشركة.", "ROOTK is not scattered tools.\nROOTK is the company’s operating system."),
    lede: tx("السيلز والمخزون والمالية والأفراد والإدارة كلها بتشتغل على نفس النظام — مش كل قسم على برنامج لوحده.", "Sales, inventory, finance, people and management all run on the same system — not each department on its own product."),
    hub: tx("ROOTK ERP", "ROOTK ERP"),
    branches: [
      {
        icon: "handshake",
        title: tx("التجاري", "Commercial"),
        items: [tx("التسويق", "Marketing"), tx("الليدز", "Leads"), tx("السيلز", "Sales"), tx("المخزون", "Inventory"), tx("المطابقة", "Matching"), tx("الحجز", "Reservation"), tx("العقد", "Contract")],
      },
      {
        icon: "ledger",
        title: tx("المالي", "Financial"),
        items: [tx("إتمام البيع", "Closed Won"), tx("خطة السداد", "Payment Plan"), tx("التحصيل", "Collections"), tx("العمولة", "Commission"), tx("الحسابات", "Accounting")],
      },
      {
        icon: "building",
        title: tx("التشغيل", "Operations"),
        items: [tx("سير العمل", "Workflows"), tx("المستندات", "Documents"), tx("الإشعارات", "Notifications"), tx("المخاطر", "Risk")],
      },
      {
        icon: "people",
        title: tx("الأفراد", "People"),
        items: [tx("الموارد البشرية", "HR"), tx("التارجت", "Targets"), tx("الأداء", "Performance"), tx("التحفيز", "Gamification")],
      },
      {
        icon: "broker",
        title: tx("المنظومة", "Ecosystem"),
        items: [tx("الوسطاء", "Brokers"), tx("المستثمرين", "Investors"), tx("المشاريع", "Projects")],
      },
      {
        icon: "radar",
        title: tx("الإدارة", "Intelligence"),
        items: [tx("التقارير", "Reports"), tx("التحليلات", "Analytics"), tx("التوقّع", "Forecast"), tx("رؤية الإدارة", "Executive Intelligence")],
      },
    ],
  },

  {
    id: "map",
    kind: "page",
    tone: "paper",
    chapter: "arch",
    layout: "layers",
    kicker: tx("02 · البنية", "02 · ARCHITECTURE"),
    title: tx("كل خطوة في ROOTK بتكمل اللي بعدها.", "Every step in ROOTK continues into the next."),
    lede: tx("من أول ليد لحد التحصيل والعمولة والحسابات — كل مرحلة بتسلّم اللي بعدها جوه نفس النظام.", "From the first Lead through collections, commission and the books — each stage hands off to the next inside the same system."),
    layers: [
      {
        title: tx("المحرك التجاري", "Commercial Engine"),
        icon: "handshake",
        steps: [
          { icon: "megaphone", title: tx("التسويق", "Marketing") },
          { icon: "lead", title: tx("الليدز", "Leads") },
          { icon: "handshake", title: tx("السيلز", "Sales") },
          { icon: "match", title: tx("المطابقة", "Matching") },
          { icon: "stack", title: tx("المخزون", "Inventory") },
          { icon: "lock", title: tx("الحجز", "Reservation") },
          { icon: "contract", title: tx("العقد", "Contract") },
          { icon: "won", title: tx("إتمام البيع", "Closed Won") },
        ],
      },
      {
        title: tx("المحرك المالي", "Financial Engine"),
        icon: "cash",
        steps: [
          { icon: "won", title: tx("إتمام البيع", "Closed Won") },
          { icon: "calendar", title: tx("خطة السداد", "Payment Plan") },
          { icon: "receipt", title: tx("التحصيل", "Collections") },
          { icon: "percent", title: tx("العمولة", "Commission") },
          { icon: "ledger", title: tx("الحسابات", "Accounting") },
        ],
      },
      {
        title: tx("محرك الإدارة", "Intelligence Engine"),
        icon: "radar",
        steps: [
          { icon: "link", title: tx("بيانات مترابطة", "Connected Data") },
          { icon: "chart", title: tx("التقارير", "Reports") },
          { icon: "chart", title: tx("التحليلات", "Analytics") },
          { icon: "radar", title: tx("رؤية الإدارة", "Executive Intelligence") },
          { icon: "decision", title: tx("القرار", "Decision") },
        ],
      },
    ],
    sats: [
      { icon: "people", title: tx("الموارد البشرية", "HR"), body: tx("الأفراد", "People") },
      { icon: "broker", title: tx("الوسطاء", "Brokers"), body: tx("المالي", "Financial") },
      { icon: "investor", title: tx("المستثمرين", "Investors"), body: tx("المالي", "Financial") },
      { icon: "building", title: tx("المشاريع", "Projects"), body: tx("التجاري", "Commercial") },
      { icon: "shield", title: tx("المخاطر", "Risk"), body: tx("التشغيل", "Operations") },
      { icon: "nodes", title: tx("سير العمل", "Workflows"), body: tx("التشغيل", "Operations") },
      { icon: "files", title: tx("المستندات", "Documents"), body: tx("التشغيل", "Operations") },
    ],
    value: tx("كل خطوة بتسلّم اللي بعدها جوه نفس النظام — مش شغل متفرّق بين برامج.", "Every step hands off to the next inside the same system — not scattered work across tools."),
  },

  {
    id: "journey",
    kind: "page",
    tone: "ink",
    chapter: "arch",
    layout: "roadmap",
    kicker: tx("02 · البنية", "02 · ARCHITECTURE"),
    title: tx("الليد مش مجرد رسالة واتساب.\nهو بداية رحلة البيع.", "A Lead is not just a WhatsApp message.\nIt is the start of the sales journey."),
    lede: tx("من أول ما الليد يدخل، ROOTK بيبدأ يبني ملف كامل للعميل — مش رسالة ضاعت في الشات.", "From the moment the Lead enters, ROOTK starts building a full client file — not a message lost in chat."),
    value: tx("كل مكالمة ومتابعة وملاحظة بتتسجل — والصورة عن فرصة البيع بتتوضح خطوة بخطوة.", "Every call, follow-up and note is recorded — and the sales opportunity gets clearer step by step."),
    steps: [
      { n: "01", icon: "megaphone", title: tx("التسويق", "Marketing"), body: tx("توليد الطلب", "Generate demand"), data: tx("بيانات الليد", "Lead Data") },
      { n: "02", icon: "lead", title: tx("الليد", "Lead"), body: tx("تسجيل الاستفسار", "Record the inquiry"), data: tx("المتطلبات", "Requirements") },
      { n: "03", icon: "assign", title: tx("التوزيع", "Assignment"), body: tx("تحديد المسؤول", "Set the owner"), data: tx("المسؤول", "Owner") },
      { n: "04", icon: "target", title: tx("التأهيل", "Qualification"), body: tx("فهم الاحتياج", "Understand the need"), data: tx("فرصة البيع", "Opportunity") },
      { n: "05", icon: "clock", title: tx("المتابعة", "Follow-up"), body: tx("إدارة التواصل", "Manage contact"), data: tx("النشاط", "Activity") },
      { n: "06", icon: "target", title: tx("فرصة البيع", "Opportunity"), body: tx("تحويله لفرصة بيع", "Turn it into a sales chance"), data: tx("اختيار الوحدة", "Unit Selection") },
      { n: "07", icon: "match", title: tx("المطابقة", "Matching"), body: tx("اقتراح الوحدات المناسبة", "Propose suitable Units"), data: tx("الوحدات المناسبة", "Suitable Units") },
      { n: "08", icon: "unit", title: tx("الوحدة", "Unit"), body: tx("اختيار الوحدة", "Select the Unit"), data: tx("الحجز", "Reservation") },
      { n: "09", icon: "lock", title: tx("الحجز", "Reservation"), body: tx("تثبيت الحجز", "Lock the reservation"), data: tx("العقد", "Contract") },
      { n: "10", icon: "contract", title: tx("العقد", "Contract"), body: tx("توثيق الصفقة", "Document the deal"), data: tx("إتمام البيع", "Closed Won") },
      { n: "11", icon: "won", title: tx("إتمام البيع", "Closed Won"), body: tx("إغلاق الصفقة", "Close the deal"), data: tx("البيانات المالية", "Financial Data") },
      { n: "12", icon: "calendar", title: tx("خطة السداد", "Payment Plan"), body: tx("بناء خطة السداد", "Build the payment plan"), data: tx("بيانات التحصيل", "Collection Data") },
      { n: "13", icon: "receipt", title: tx("التحصيل", "Collections"), body: tx("متابعة التحصيل", "Follow collections"), data: tx("بيانات العمولة", "Commission Data") },
      { n: "14", icon: "percent", title: tx("العمولة", "Commission"), body: tx("حساب العمولة", "Calculate commission"), data: tx("بيانات الحسابات", "Accounting Data") },
      { n: "15", icon: "ledger", title: tx("الحسابات", "Accounting"), body: tx("بيتسجل في الحسابات", "Posted to the books"), data: tx("بيانات مؤشرات الأداء", "KPI Data") },
      { n: "16", icon: "radar", title: tx("رؤية الإدارة", "Executive Intelligence"), body: tx("الرؤية والقرار", "Visibility and decision") },
    ],
  },

  {
    id: "marketing",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "funnel",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("الحملة الناجحة مش اللي جابت ليدز أكتر.\nالحملة الناجحة اللي قفلت صفقات أكتر.", "A successful campaign is not the one that brought more Leads.\nIt is the one that closed more deals."),
    lede: tx("تكلفة الليد ونسبة التحويل والإيراد والعائد بيتقاسوا من الحملة لحد الصفقة اللي اتقفلت — على نفس المسار.", "CPL, conversion, revenue and return are measured from campaign to the deal that closed — on the same path."),
    steps: [
      { icon: "megaphone", title: tx("الحملة", "Campaign"), body: tx("مصدر الطلب", "Source of demand") },
      { icon: "lead", title: tx("التقاط الليد", "Lead Capture"), body: tx("تسجيل الاستفسار", "Capture the inquiry") },
      { icon: "link", title: tx("الإسناد", "Attribution"), body: tx("ربط المصدر بالنتيجة", "Tie source to result") },
      { icon: "handshake", title: tx("السيلز", "Sales"), body: tx("شغل السيلز", "Sales work") },
      { icon: "target", title: tx("التحويل", "Conversion"), body: tx("تحول الفرصة", "Opportunity converts") },
      { icon: "won", title: tx("إتمام البيع", "Closed Won"), body: tx("إغلاق الصفقة", "Deal closes") },
      { icon: "cash", title: tx("الإيراد", "Revenue"), body: tx("قيمة الصفقة", "Deal value") },
      { icon: "chart", title: tx("العائد", "ROI"), body: tx("عائد الحملة", "Campaign return") },
    ],
    value: tx("الحملة بتتقاس على الصفقات اللي قفلتها، مش على عدد الليدز بس.", "The campaign is measured by the deals it closed, not Lead count alone."),
  },

  {
    id: "leads",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "leadlife",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("كل ليد ليه مسؤول، خطوة جاية، ومرحلة واضحة.", "Every Lead has an owner, a next step, and a clear stage."),
    lede: tx("مين ماسك الملف، إيه الخطوة الجاية، وإيه المرحلة — من غير ما الليد يتوه بين التيم.", "Who owns the file, what happens next, and which stage — without the Lead getting lost between the team."),
    life: [
      { icon: "lead", title: tx("تم تسجيل الليد", "Lead Captured"), sales: tx("يشوف الاستفسار", "Sees the inquiry"), records: [tx("المصدر", "Source"), tx("الحملة", "Campaign")] },
      { icon: "shield", title: tx("كشف التكرار", "Duplicate Check"), sales: tx("ما يشتغلش على تكرار", "Does not work a duplicate"), records: [tx("المطابقة", "Match")] },
      { icon: "assign", title: tx("التوزيع", "Assignment"), sales: tx("يعرف مين المسؤول", "Knows the owner"), records: [tx("المسؤول", "Owner")] },
      { icon: "employee", title: tx("المسؤول", "Owner"), sales: tx("يمسك الملف", "Takes the file"), records: [tx("المسؤولية", "Ownership")] },
      { icon: "activity", title: tx("الأنشطة", "Activities"), sales: tx("يسجّل الحركة", "Logs the motion"), records: [tx("الملاحظات", "Notes"), tx("المكالمات", "Calls")] },
      { icon: "clock", title: tx("المتابعة", "Follow-up"), sales: tx("يحافظ على التواصل", "Keeps contact alive"), records: [tx("الخطوة الجاية", "Next action")] },
      { icon: "target", title: tx("التأهيل", "Qualification"), sales: tx("يفهم احتياج العميل", "Understands the need"), records: [tx("المتطلبات", "Requirements"), tx("الفيدباك", "Feedback"), tx("المتابعة الجاية", "Next Follow-up"), tx("سجل المرحلة", "Stage History")] },
      { icon: "nodes", title: tx("البايبلاين", "Pipeline"), sales: tx("يحرك المرحلة", "Moves the stage"), records: [tx("المرحلة", "Stage")] },
      { icon: "handshake", title: tx("فرصة البيع", "Opportunity"), sales: tx("يفتح فرصة بيع", "Opens a sales chance"), records: [tx("فرصة البيع", "Opportunity")] },
      { icon: "chat", title: tx("الفيدباك", "Feedback"), sales: tx("يثبّت الملاحظات", "Locks the notes"), records: [tx("الفيدباك", "Feedback")] },
    ],
    value: tx("كل مكالمة ومتابعة وملاحظة بتتسجل — والصورة عن فرصة البيع بتتوضح خطوة بخطوة.", "Every call, follow-up and note is recorded — and the sales opportunity gets clearer step by step."),
  },

  {
    id: "pipeline",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "pipeline",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("البايبلاين مش مجرد مراحل محفوظة.\nهو مسار البيع من أول لآخر.", "The Pipeline is not just saved stages.\nIt is the full sales path from start to close."),
    lede: tx("كل مرحلة ليها شغل مطلوب، وشروط واضحة، وخطوة تالية — من أول ليد لحد إتمام البيع.", "Every stage has required work, clear conditions, and a next step — from the first Lead through closing."),
    pipe: [
      { n: "01", icon: "lead", title: tx("ليد جديد", "Fresh Lead"), purpose: tx("دخول الطلب للنظام", "Demand enters the system"), next: tx("تم التواصل", "Contacted") },
      { n: "02", icon: "chat", title: tx("تم التواصل", "Contacted"), purpose: tx("أول تواصل فعلي", "First real contact"), next: tx("مؤهّل", "Qualified") },
      { n: "03", icon: "target", title: tx("مؤهّل", "Qualified"), purpose: tx("العميل مؤهل للانتقال لفرصة بيع", "The client is ready to become an opportunity"), next: tx("فرصة / مطابقة", "Opportunity / Matching") },
      { n: "04", icon: "match", title: tx("فرصة / مطابقة", "Opportunity / Matching"), purpose: tx("ربط الاحتياج بالمخزون", "Tie need to inventory"), next: tx("اجتماع", "Meeting") },
      { n: "05", icon: "handshake", title: tx("اجتماع", "Meeting"), purpose: tx("اجتماع قرار أو معاينة", "Decision meeting or viewing"), next: tx("الحجز", "Reservation") },
      { n: "06", icon: "lock", title: tx("الحجز", "Reservation"), purpose: tx("تثبيت الوحدة", "Lock the Unit"), next: tx("إتمام البيع", "Closed Won") },
      { n: "07", icon: "won", title: tx("إتمام البيع", "Closed Won"), purpose: tx("إغلاق البيع وبدء دورة المال", "Close the sale and start the money cycle"), next: tx("عقد / مالية", "Contract / Finance") },
    ],
  },

  {
    id: "inventory",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "inventory",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("المخزون هو مرجع كل الوحدات في الشركة.", "Inventory is the reference for every unit in the company."),
    lede: tx("اختيار الوحدة مش منفصل عن المخزون. السيلز بيعرف فورًا إيه المتاح، إيه المحجوز، وإيه اللي اتباع.", "Selecting a unit is not separate from inventory. Sales knows immediately what is available, reserved, or sold."),
    tree: [
      { icon: "building", title: tx("المطوّر", "Developer") },
      { icon: "building", title: tx("المشروع", "Project") },
      { icon: "stack", title: tx("العمارة", "Building") },
      { icon: "unit", title: tx("الدور", "Floor") },
      { icon: "unit", title: tx("الوحدة", "Unit") },
    ],
    status: [
      { icon: "stack", title: tx("متاح", "Available") },
      { icon: "lock", title: tx("محجوز", "Reserved") },
      { icon: "contract", title: tx("محجوز مؤكد", "Booked") },
      { icon: "won", title: tx("مباع", "Sold") },
    ],
    ties: [
      { icon: "lead", title: tx("الليد", "Lead") },
      { icon: "target", title: tx("فرصة البيع", "Opportunity") },
      { icon: "match", title: tx("المطابقة", "Matching") },
      { icon: "lock", title: tx("الحجز", "Reservation") },
      { icon: "contract", title: tx("العقد", "Contract") },
      { icon: "calendar", title: tx("خطة السداد", "Payment Plan") },
      { icon: "handshake", title: tx("السيلز", "Sales") },
    ],
    value: tx("السيلز مش بيشتغل بعيد عن المخزون؛ كل اختيار أو حجز أو بيع مربوط بحالة الوحدة الفعلية.", "Sales does not work apart from inventory; every selection, reservation or sale is tied to the actual unit status."),
  },

  {
    id: "match",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "match",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("العميل يقول عايز إيه…\nROOTK يطلّع أنسب الوحدات.", "The client says what they need.\nROOTK returns the most suitable units."),
    lede: tx("الميزانية والموقع والمساحة وخطة السداد بتتحول لقائمة وحدات مناسبة — وبعدين اختيار السيلز والحجز.", "Budget, location, area and payment plan become a list of suitable units — then Sales selection and reservation."),
    req: [
      { icon: "cash", title: tx("الميزانية", "Budget") },
      { icon: "unit", title: tx("المساحة", "Area") },
      { icon: "building", title: tx("الموقع", "Location") },
      { icon: "stack", title: tx("غرف النوم", "Bedrooms") },
      { icon: "building", title: tx("المشروع", "Project") },
      { icon: "calendar", title: tx("خطة السداد", "Payment Plan") },
    ],
    out: [
      { icon: "unit", title: tx("وحدة أ", "Unit A") },
      { icon: "unit", title: tx("وحدة ب", "Unit B") },
      { icon: "unit", title: tx("وحدة ج", "Unit C") },
    ],
    value: tx("السيلز مش بيدوّر بعشوائية؛ بيشتغل على وحدات مطابقة لطلب العميل.", "Sales does not hunt at random; they work units that match the client’s need."),
  },

  {
    id: "reserve",
    kind: "page",
    tone: "paper",
    chapter: "comm",
    layout: "reserve",
    kicker: tx("03 · التجاري", "03 · COMMERCIAL"),
    title: tx("من اختيار الوحدة للحجز الفعلي — كل خطوة محسوبة.", "From selecting the unit to an actual reservation — every step is accounted for."),
    lede: tx("الحجز بيأثر فورًا على حالة الوحدة. فيه فرق بين طلب معلّق وحجز معتمد بيقفل المخزون.", "Reservation changes the unit’s status immediately. There is a difference between a pending request and an approved lock."),
    left: [
      { icon: "lead", title: tx("الليد", "Lead") },
      { icon: "unit", title: tx("الوحدة", "Unit") },
      { icon: "employee", title: tx("مسؤول السيلز", "Sales Owner") },
    ],
    steps: [
      { icon: "stack", title: tx("متاح", "Available") },
      { icon: "target", title: tx("اتختار", "Selected") },
      { icon: "won", title: tx("الاعتماد", "Approval") },
      { icon: "lock", title: tx("قفل المخزون", "Inventory Lock") },
      { icon: "lock", title: tx("محجوز", "Reserved") },
      { icon: "calendar", title: tx("خطة السداد", "Payment Plan") },
      { icon: "contract", title: tx("العقد", "Contract") },
    ],
    right: [{ icon: "stack", title: tx("حالة المخزون", "Inventory Status"), body: tx("متاح ← محجوز", "Available → Reserved") }],
    value: tx("الحجز مش مجرد تغيير حالة على الشاشة؛ هو خطوة بتحمي المخزون وتجهّزه للمرحلة اللي بعدها.", "A reservation is not just a status change on screen; it protects inventory and prepares the next stage of the sale."),
  },

  {
    id: "closed",
    kind: "page",
    tone: "ink",
    chapter: "erp",
    layout: "branch",
    kicker: tx("04 · ERP", "04 · ERP"),
    title: tx("بعد قفل الصفقة… الشغل بيكمل للمالية والتشغيل.", "After the deal closes… work continues into finance and operations."),
    lede: tx("لما الصفقة تتقفل، بيانات البيع بتكمل لوحدها: عقد، خطة سداد، تحصيل، عمولة، حسابات، وبورتال للمستثمر.", "When the deal closes, sales data continues on its own: contract, payment plan, collections, commission, accounting, and an investor portal."),
    hub: tx("إتمام البيع", "CLOSED WON"),
    branches: [
      { icon: "contract", title: tx("العقد", "Contract"), items: [tx("توثيق الاتفاق", "Document the agreement")] },
      { icon: "calendar", title: tx("خطة السداد", "Payment Plan"), items: [tx("جدول الأقساط", "Installment schedule")] },
      { icon: "receipt", title: tx("التحصيل", "Collections"), items: [tx("متابعة التحصيل", "Follow collections")] },
      { icon: "percent", title: tx("العمولة", "Commission"), items: [tx("حساب العمولة", "Calculate commission")] },
      { icon: "ledger", title: tx("الحسابات", "Accounting"), items: [tx("بيتسجل في الحسابات", "Posted to the books")] },
      { icon: "investor", title: tx("المستثمر", "Investor"), items: [tx("العلاقة بتكمل بعد البيع", "The relationship continues after the sale")] },
    ],
    value: tx("إتمام البيع مش نهاية الشغل. هو بداية العقد والتحصيل والعمولة والحسابات.", "Closing the sale is not the end of the work. It is the start of contract, collections, commission and accounting."),
  },

  {
    id: "collect",
    kind: "page",
    tone: "paper",
    chapter: "erp",
    layout: "collect",
    kicker: tx("04 · ERP", "04 · ERP"),
    title: tx("بعد البيع، خطة السداد تفضل شغّالة جوه نفس النظام.", "After the sale, the payment plan keeps running inside the same system."),
    lede: tx("التحصيل مش شغل منفصل عن البيع. الأقساط، التنبيهات، الدفع من بورتال المستثمر، وإدارة الشيكات — كلها على نفس الصفقة.", "Collections is not separate from the sale. Installments, reminders, investor-portal payments and cheque management all sit on the same deal."),
    steps: [
      { icon: "contract", title: tx("العقد", "Contract") },
      { icon: "calendar", title: tx("خطة السداد", "Payment Plan") },
      { icon: "cash", title: tx("الأقساط", "Installments") },
      { icon: "clock", title: tx("الاستحقاق", "Due Dates") },
      { icon: "receipt", title: tx("الدفعات", "Payments") },
      { icon: "files", title: tx("الإيصالات", "Receipts") },
      { icon: "chart", title: tx("المتبقي", "Outstanding") },
      { icon: "radar", title: tx("حالة التحصيل", "Collection Status") },
    ],
    right: [
      { icon: "handshake", title: tx("السيلز", "Sales") },
      { icon: "ledger", title: tx("المالية", "Finance") },
      { icon: "radar", title: tx("الإدارة", "Management") },
    ],
    value: tx("فريق التحصيل يتابع المستحق والمدفوع والمتأخر والشيكات من نفس الصفقة — والمستثمر يدفع ويتابع من البوابة.", "Collections follows due, paid, overdue and cheques on the same deal — and the investor tracks and pays from the portal."),
  },

  {
    id: "commission",
    kind: "page",
    tone: "paper",
    chapter: "erp",
    layout: "commission",
    kicker: tx("04 · ERP", "04 · ERP"),
    title: tx("العمولة بتتحسب وتتوزع وتتحصل من نفس الصفقة.", "Commission is calculated, split and collected from the same deal."),
    lede: tx("من أول ما الصفقة تتقفل، العمولة بتتوزع أوتوماتيك حسب نسب السيلز والتيم ليدر والمانجر والدايركتور والبروكر والشركة.", "The moment the deal closes, commission is split automatically across sales, team leader, manager, director, broker, and the company."),
    steps: [
      { icon: "won", title: tx("إتمام البيع", "Closed Won") },
      { icon: "nodes", title: tx("قاعدة العمولة", "Commission Rule") },
      { icon: "percent", title: tx("الحساب", "Calculation") },
      { icon: "ledger", title: tx("الضريبة", "Tax / VAT") },
      { icon: "broker", title: tx("التوزيع", "Distribution") },
      { icon: "calendar", title: tx("جدول الأقساط", "Installment Schedule") },
      { icon: "receipt", title: tx("الإيصالات", "Receipts") },
      { icon: "cash", title: tx("مستحق الدفع", "Payable") },
      { icon: "ledger", title: tx("ترحيل اختياري للحسابات", "Optional GL posting") },
    ],
    roles: [
      { icon: "employee", title: tx("السيلز", "Sales") },
      { icon: "people", title: tx("مبيعات غير مباشرة", "Indirect Sales") },
      { icon: "broker", title: tx("الوسيط", "Broker") },
      { icon: "employee", title: tx("تيم ليدر", "Team Leader") },
      { icon: "handshake", title: tx("مدير مبيعات", "Sales Manager") },
      { icon: "radar", title: tx("دايركتور المبيعات", "Sales Director") },
    ],
  },

  {
    id: "finance",
    kind: "page",
    tone: "paper",
    chapter: "erp",
    layout: "accounting",
    kicker: tx("04 · ERP", "04 · ERP"),
    title: tx("كل صفقة ودفعة وعمولة بتظهر في الحسابات بوضوح.", "Every deal, payment and commission shows clearly in the books."),
    lede: tx("الصفقة والعمولة ودفعات العميل والرواتب بيوصلوا للحسابات أوتوماتيك — مش شغل يدوي بعد البيع.", "The deal, commission, client payments and payroll reach accounting automatically — not manual work after the sale."),
    left: [
      { icon: "won", title: tx("الصفقة", "Deal") },
      { icon: "cash", title: tx("الإيراد", "Revenue") },
      { icon: "receipt", title: tx("التحصيل", "Collections") },
      { icon: "percent", title: tx("العمولة", "Commission") },
    ],
    right: [
      { icon: "ledger", title: tx("دفتر الأستاذ", "General Ledger") },
      { icon: "chart", title: tx("التقارير", "Reports") },
    ],
    value: tx("المالية بتستلم الأرقام من نفس النظام — مش بتبدأ الشغل من صفر بعد البيع.", "Finance receives the numbers from the same system — it does not start from zero after the sale."),
  },

  {
    id: "people",
    kind: "page",
    tone: "paper",
    chapter: "eco",
    layout: "people",
    kicker: tx("05 · المنظومة", "05 · ECOSYSTEM"),
    title: tx("كل حركة السيلز على الليد…\nبتتحول لتقرير أداء يومي. بضغطة زر.", "Every sales action on a Lead\nbecomes a daily performance report. One click."),
    lede: tx("بمجرد ما السيلز يشتغل على الليدز، ROOTK بيطلع تقارير أداء يومية دقيقة للفريق كله. ومعاها تقارير الحسابات والتارجت والتاسكات — وتقدر تعمل تاسك بمسؤول وميعاد ومتابعة.", "The moment sales work the leads, ROOTK produces precise daily performance reports for the whole team. Plus accounting, target and task reports — and you can create a task with owner, due date and follow-up."),
    left: [
      { icon: "employee", title: tx("الموظف", "Employee") },
      { icon: "activity", title: tx("الأنشطة", "Activities") },
      { icon: "won", title: tx("الصفقات", "Deals") },
      { icon: "target", title: tx("التارجت", "Targets") },
      { icon: "chart", title: tx("الإنجاز", "Achievement") },
      { icon: "radar", title: tx("الأداء", "Performance") },
      { icon: "trophy", title: tx("التحفيز", "Gamification") },
    ],
    right: [
      { icon: "employee", title: tx("الموظف", "Employee") },
      { icon: "clock", title: tx("الحضور", "Attendance") },
      { icon: "calendar", title: tx("الإجازات", "Leave") },
      { icon: "cash", title: tx("الرواتب", "Payroll") },
      { icon: "radar", title: tx("الأداء", "Performance") },
    ],
    center: tx("أداء الموظف", "Employee Performance"),
    value: tx("التقرير مش شغل آخر اليوم. هو ناتج شغل السيلز على الليد — يومي، دقيق، وجاهز بضغطة زر.", "The report is not end-of-day homework. It is the product of sales work on the Lead — daily, precise, and ready in one click."),
  },

  {
    id: "partners",
    kind: "page",
    tone: "paper",
    chapter: "eco",
    layout: "dual",
    kicker: tx("05 · المنظومة", "05 · ECOSYSTEM"),
    title: tx("تواصل الشركة والعميل…\nجوه ROOTK — مش على واتساب ضايع.", "Company and client communication…\ninside ROOTK — not lost on WhatsApp."),
    lede: tx("شات داخلي بين الشركة كلها، والأدمن مطّلع على المحادثات. وكمان شات بين الإدارة والدعم الفني والعملاء — جنب بورتال المستثمر.", "An internal chat across the whole company, with admin visibility over the conversations. Plus chat between management, technical support and clients — next to the investor portal."),
    left: [
      { icon: "chat", title: tx("الشات الداخلي", "Internal Chat") },
      { icon: "people", title: tx("الشركة", "Company") },
      { icon: "shield", title: tx("رقابة الأدمن", "Admin Oversight") },
    ],
    right: [
      { icon: "chat", title: tx("شات العميل", "Client Chat") },
      { icon: "radar", title: tx("الإدارة", "Management") },
      { icon: "people", title: tx("الدعم", "Support") },
      { icon: "investor", title: tx("بورتال المستثمر", "Investor Portal") },
    ],
    center: tx("تواصل موحّد", "UNIFIED COMMUNICATION"),
    value: tx("المحادثات جوه النظام: الداخلي للأدمن ظاهر، وشات العميل والدعم من نفس المنظومة — من غير شغل على واتساب برّه.", "Conversations live in the system: internal chat is visible to admin, and client–support chat runs in the same environment — not outside on WhatsApp."),
  },

  {
    id: "control",
    kind: "page",
    tone: "paper",
    chapter: "eco",
    layout: "event",
    kicker: tx("05 · المنظومة", "05 · ECOSYSTEM"),
    title: tx("لما يحصل حدث في النظام… ROOTK يعرف الخطوة اللي بعدها.", "When something happens in the system… ROOTK knows the next step."),
    lede: tx("إتمام البيع مش مجرد تغيير مرحلة. بيحدّث حالة الوحدة، يجهّز خطة السداد، يحرّك التحصيل والعمولة، ويسجّل اللي حصل.", "Closing is not just a stage change. It updates the unit, prepares the payment plan, moves collections and commission, and logs what happened."),
    event: {
      trigger: tx("تم إنشاء الليد", "Lead Created"),
      cond: tx("قاعدة البيزنس", "Business Rule"),
      actions: [
        { n: "01", icon: "assign", title: tx("تعيين مسؤول", "Assign Manager") },
        { n: "02", icon: "activity", title: tx("إنشاء تاسك", "Create Task") },
        { n: "03", icon: "bell", title: tx("إرسال إشعار", "Send Notification") },
      ],
      audit: tx("تسجيل النشاط", "Record Activity"),
    },
    eventB: [
      { icon: "nodes", title: tx("تغيّر المرحلة", "Stage Changed") },
      { icon: "clock", title: tx("إنشاء متابعة", "Create Follow-up") },
      { icon: "bell", title: tx("إشعار المسؤول", "Notify Owner") },
      { icon: "files", title: tx("تسجيل الحدث", "Log Event") },
    ],
  },

  {
    id: "intel",
    kind: "page",
    tone: "ink",
    chapter: "intel",
    layout: "truth",
    kicker: tx("06 · الإدارة", "06 · INTELLIGENCE"),
    title: tx("كل أقسام الشركة بتدخل على ROOTK.\nوالإدارة تشوف الصورة كاملة.", "Every department feeds into ROOTK.\nManagement sees the full picture."),
    lede: tx("الإدارة مش محتاجة تجمع أرقام من أكتر من قسم. كل قسم بيشتغل على نفس مصدر البيانات.", "Management does not need to assemble numbers from several departments. Every department works on the same data source."),
    hub: tx("بيانات ROOTK المترابطة", "CONNECTED ROOTK DATA"),
    branches: [
      { icon: "megaphone", title: tx("التسويق", "Marketing"), items: [] },
      { icon: "handshake", title: tx("السيلز", "Sales"), items: [] },
      { icon: "stack", title: tx("المخزون", "Inventory"), items: [] },
      { icon: "building", title: tx("المشاريع", "Projects"), items: [] },
      { icon: "ledger", title: tx("الحسابات", "Accounting"), items: [] },
      { icon: "receipt", title: tx("التحصيل", "Collections"), items: [] },
      { icon: "people", title: tx("الموارد البشرية", "HR"), items: [] },
      { icon: "investor", title: tx("المستثمرين", "Investors"), items: [] },
      { icon: "broker", title: tx("الوسطاء", "Brokers"), items: [] },
    ],
    steps: [
      { icon: "link", title: tx("بيانات مترابطة", "Connected Data") },
      { icon: "chart", title: tx("التقارير", "Reporting") },
      { icon: "radar", title: tx("رؤية الإدارة", "Executive Intelligence") },
      { icon: "decision", title: tx("القرار", "Decision") },
    ],
  },

  {
    id: "roles",
    kind: "page",
    tone: "ink",
    chapter: "intel",
    layout: "intel",
    kicker: tx("06 · الإدارة", "06 · INTELLIGENCE"),
    title: tx("كل مدير يشوف الجزء اللي يخصه…\nوالإدارة تشوف الشركة كلها.", "Each director sees the part that concerns them.\nLeadership sees the whole company."),
    lede: tx("كل دور شايف نطاقه. والشاشات والصلاحيات في ROOTK قابلة للتخصيص حسب شغل الشركة — والإدارة تشوف الصورة الكاملة.", "Each role sees its scope. Screens and permissions in ROOTK are customizable to how the company works — leadership still sees the full picture."),
    hub: tx("رؤية الإدارة", "EXECUTIVE INTELLIGENCE"),
    branches: [
      { icon: "megaphone", title: tx("التسويق", "Marketing"), items: [tx("الحملات", "Campaigns"), tx("الإسناد", "Attribution"), tx("تكلفة الليد", "CPL"), tx("التحويل", "Conversion"), tx("العائد", "ROI")] },
      { icon: "handshake", title: tx("السيلز", "Sales"), items: [tx("الليدز", "Leads"), tx("البايبلاين", "Pipeline"), tx("المتابعة", "Follow-up"), tx("الصفقات", "Deals"), tx("الأداء", "Performance")] },
      { icon: "ledger", title: tx("المالية", "Finance"), items: [tx("الإيراد", "Revenue"), tx("التحصيل", "Collections"), tx("العمولة", "Commission"), tx("الحسابات", "Accounting")] },
      { icon: "building", title: tx("التشغيل", "Operations"), items: [tx("المشاريع", "Projects"), tx("المخزون", "Inventory"), tx("الإنشاءات", "Construction"), tx("المخاطر", "Risk")] },
      { icon: "people", title: tx("الموارد البشرية", "HR"), items: [tx("الموظفين", "Employees"), tx("الحضور", "Attendance"), tx("الرواتب", "Payroll"), tx("الأداء", "Performance")] },
      { icon: "investor", title: tx("المستثمرين", "Investors"), items: [tx("العقود", "Contracts"), tx("الأقساط", "Installments"), tx("الدفعات", "Payments"), tx("المحفظة", "Portfolio")] },
    ],
    value: tx("الأدوار والصلاحيات والتخصيص بيتظبطوا على شغل الشركة.", "Roles, permissions and customization are set to how the company works."),
  },

  {
    id: "why",
    kind: "page",
    tone: "paper",
    chapter: "intel",
    layout: "outcomes",
    kicker: tx("06 · الإدارة", "06 · INTELLIGENCE"),
    title: tx("إيه اللي بيتغير فعليًا لما الشركة تشتغل على ROOTK؟", "What actually changes when the company operates on ROOTK?"),
    lede: tx("الهدف مش برامج أكتر. الهدف شغل أوضح للشركة.", "The aim is not more software. The aim is clearer work for the company."),
    hub: tx("ROOTK", "ROOTK"),
    why: [
      { n: "01", icon: "link", title: tx("تشغيل واحد مترابط", "ONE CONNECTED OPERATION"), body: tx("الشغل مربوط من أول ليد لآخر قيد في الحسابات.", "Work is tied from the first Lead to the last posting in the books.") },
      { n: "02", icon: "handshake", title: tx("بايبلاين بيع واضح", "CLEAR SALES PIPELINE"), body: tx("كل ليد ليه مسؤول ومتابعة وخطوة جاية.", "Every Lead has an owner, follow-up and next step.") },
      { n: "03", icon: "stack", title: tx("مخزون مترابط", "CONNECTED INVENTORY"), body: tx("الوحدة اللي بتتباع هي نفس الوحدة في المخزون.", "The unit being sold is the same unit in inventory.") },
      { n: "04", icon: "receipt", title: tx("تحصيل مضبوط", "CONTROLLED COLLECTIONS"), body: tx("كل قسط مربوط بالعقد والصفقة.", "Every installment is tied to the contract and the deal.") },
      { n: "05", icon: "percent", title: tx("عمولات قابلة للتتبع", "TRACEABLE COMMISSIONS"), body: tx("العمولة امتداد للصفقة — مش ملف إكسل على جمب.", "Commission is an extension of the deal — not an Excel file on the side.") },
      { n: "06", icon: "ledger", title: tx("بيانات مالية مترابطة", "CONNECTED FINANCIAL DATA"), body: tx("أرقام الحسابات بتيجي من نفس الصفقة والدفعات.", "Accounting numbers come from the same deal and payments.") },
      { n: "07", icon: "radar", title: tx("رؤية إدارية كاملة", "EXECUTIVE VISIBILITY"), body: tx("الإدارة تشوف الصورة من بيانات التشغيل الفعلية.", "Leadership sees the picture from actual operating data.") },
    ],
    value: tx("الهدف مش إن الشركة تستخدم برامج أكتر. الهدف إنها تدير شغلها أوضح وأسرع.", "The aim is not for the company to use more software. The aim is to run the business more clearly and faster."),
  },

  { id: "close", kind: "close", tone: "ink", chapter: "close" },
];
